security:
    enable_authenticator_manager: true

    #   класс пользователя, авторизация происходит по значению свойства login
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    #   отвечает за хеширование паролей
    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # выход из личного кабинета доступен по ссылке /logout
            logout:
                path: logout
            # класс, отвечающий за авторизацию

            custom_authenticators:
                 - App\Security\Authenticator

            # check_path: /auth - куда уходит аякс запрос
            json_login:
                check_path: /auth


    #  если для выполнения запросы нужна авторизация,
    #  перенаправление будет осуществляться по ссылке, указанной в getLoginUrl
    # класса App\Security\Authenticator
    access_control:
